language: node_js

os:
  - linux
  - osx

node_js:
  - '10'
  - '8'
  - '6'

install:
  - npm i -g npm@latest
  - npm install

after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
